#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another p>
FILE=/etc/nginx/sites-available/default
REDIRECT="location /redirect_me {\n return 301 https://www.youtube.com/watch?v>

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx start
sudo sed -i "37i $REDIRECT" $FILE
service nginx stop
service nginx start
