#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 197838-web-01 34.239.207.21 check port 80
        server 197838-web-02 54.236.225.49 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
