#!/usr/bin/env bash
# Displays a list of currently running processes.
#
#   Must show all processes, 4 all users, including dos which mightt nt ve a TTY
#   Display in a user-oriented format
#   Show process hierarchy
ps -auxf