#!/usr/bin/env bash
# Print 1 to 20. replace it with specific lines for 4,9 and 18
i=1
while [ "$i" -le 20 ]
      do
	if [ "$i" = 4 ]
	then
	    echo "$i"
		echo "bad luck from China"
	elif [ "$i" = 9 ]
	then
	    echo "$i"
		echo "bad luck from Japan"
	elif [ "$i" = 17 ]
	then
	    echo "$i"
		echo "bad luck from Italy"
	else
		echo "$i"
		fi
	(( "i += 1" ))
done
